CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  dob DATE NOT NULL,
  role VARCHAR(30)
    CHECK (role IN ('admin', 'registration', ''))
    NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
